import { SPK, PriceCatalogItem, Vendor, Mandor, MandorPaymentRequest, UserProfile, ApprovalLog, ApprovalRulesConfig } from '@/types';

export const DEFAULT_APPROVAL_RULES: ApprovalRulesConfig = {
  spkMarginThreshold: 20, // Margin minimum 20% untuk approval mandiri PM, dibawah 20% butuh Direktur
  poTier1Limit: 15000000, // PO Material sampai Rp 15 Juta cukup PM, diatas 15 Juta butuh PM + Direktur
  maxKasbonPercent: 30, // Maksimal kasbon 30% dari total nilai borongan
  term1MinProgress: 20, // Syarat fisik Termin 1: minimal 20%
  term2MinProgress: 60, // Syarat fisik Termin 2: minimal 60%
  term3MinProgress: 100, // Syarat fisik Termin 3: 100% (QC & BAST)
  requirePhotoOnDpr: true,
  autoNotifyWhatsApp: true,
  allowMandorOverdraft: false,
};

export const AVAILABLE_USERS: UserProfile[] = [
  {
    id: 'usr-pm',
    name: 'Teguh Prayoga, S.T.',
    role: 'PROJECT_MANAGER',
    roleLabel: 'Project Manager (PM)',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    email: 'pm@indotek.co.id',
    password: 'password123',
    phone: '0812-3456-7890',
    status: 'ACTIVE',
    department: 'Divisi Operasional & Lapangan',
    description: 'Penanggung jawab teknis, rilis SPK Mandor, verifikasi progres DPR & approval teknis lapangan.',
    createdAt: '2026-01-15',
    permissions: [
      'APPROVE_SPK_MANDOR',
      'APPROVE_MATERIAL_PO_L1',
      'APPROVE_PAYMENT_REQUEST_L1',
      'VERIFY_DAILY_PROGRESS',
      'VIEW_PORTFOLIO_SUMMARY',
    ],
  },
  {
    id: 'usr-estimator',
    name: 'Budhimansyah',
    role: 'ESTIMATOR',
    roleLabel: 'Cost Estimator / Commercial',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    email: 'estimator@indotek.co.id',
    password: 'password123',
    phone: '0813-8899-7711',
    status: 'ACTIVE',
    department: 'Divisi Estimasi & Komersial',
    description: 'Pengolah BOQ SPK Vendor, setting harga borongan jasa & material, analisa target profit margin.',
    createdAt: '2026-02-01',
    permissions: [
      'CREATE_EDIT_CLUSTER_BOQ',
      'IMPORT_EXCEL_BOQ',
      'SET_MANDOR_RATES',
      'DRAFT_SPK_MANDOR',
      'MANAGE_PRICE_CATALOG',
    ],
  },
  {
    id: 'usr-finance',
    name: 'Sri Wahyuni, S.E.',
    role: 'FINANCE',
    roleLabel: 'Finance & Treasury',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
    email: 'finance@indotek.co.id',
    password: 'password123',
    phone: '0815-6677-8899',
    status: 'ACTIVE',
    department: 'Divisi Keuangan & Kasir',
    description: 'Validasi syarat pencairan dana termin & kasbon, eksekusi transfer supplier/mandor, pembukuan voucher.',
    createdAt: '2026-01-10',
    permissions: [
      'APPROVE_EXECUTE_PAYMENT',
      'TRANSFER_PO_SUPPLIER',
      'PRINT_PAYMENT_VOUCHERS',
      'MANAGE_KASBON_LEDGER',
      'VIEW_FINANCIAL_REPORTS',
    ],
  },
  {
    id: 'usr-procurement',
    name: 'Rizky Pratama',
    role: 'PROCUREMENT',
    roleLabel: 'Procurement & Logistik',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    email: 'procurement@indotek.co.id',
    password: 'password123',
    phone: '0819-2233-4455',
    status: 'ACTIVE',
    department: 'Divisi Pengadaan & Gudang',
    description: 'Penerbitan PO material aksesoris ke toko/supplier, kontrol stok gudang, serah terima BAST Mandor.',
    createdAt: '2026-03-01',
    permissions: [
      'CREATE_MATERIAL_PO',
      'RECEIVE_GOODS_WAREHOUSE',
      'ISSUE_SURAT_JALAN_MANDOR',
      'MANAGE_SUPPLIERS',
      'TRACK_MATERIAL_USAGE',
    ],
  },
  {
    id: 'usr-admin',
    name: 'Ir. Bambang Sugianto',
    role: 'SUPER_ADMIN',
    roleLabel: 'Direktur Utama / Super Admin',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
    email: 'direktur@indotek.co.id',
    password: 'password123',
    phone: '0811-9988-7766',
    status: 'ACTIVE',
    department: 'Management & Direksi',
    description: 'Otoritas tertinggi, pengawasan portfolio multi-vendor, override approval darurat, audit trail.',
    createdAt: '2025-10-01',
    permissions: [
      'ALL_PERMISSIONS',
      'OVERRIDE_APPROVALS',
      'MANAGE_MASTER_DATA',
      'VIEW_PROFIT_LOSS',
      'SYSTEM_ADMINISTRATION',
    ],
  },
];

export const INITIAL_APPROVAL_LOGS: ApprovalLog[] = [
  {
    id: 'app-log-1',
    entityType: 'SPK_MANDOR',
    entityId: 'spk-pemalang',
    entityTitle: 'Rilis SPK Mandor - Cluster Pemalang',
    action: 'APPROVED',
    actedByRole: 'PROJECT_MANAGER',
    actedByName: 'Teguh Prayoga, S.T.',
    timestamp: '2026-08-11 10:15',
    notes: 'Estimasi margin 37.7% sehat dan alokasi mandor Pak Fatrah disetujui.',
  },
  {
    id: 'app-log-2',
    entityType: 'MATERIAL_PO',
    entityId: 'po-mat-001',
    entityTitle: 'PO Aksesoris FO CV Surya (PO-MAT/2026/08/001)',
    action: 'APPROVED',
    actedByRole: 'PROJECT_MANAGER',
    actedByName: 'Teguh Prayoga, S.T.',
    timestamp: '2026-08-13 16:30',
    notes: 'Budget aksesoris sesuai BOQ site Sukaperna.',
  },
  {
    id: 'app-log-3',
    entityType: 'PAYMENT_REQUEST',
    entityId: 'req-002',
    entityTitle: 'Kasbon Operasional Mandor Sugeng - Tegal Slawi',
    action: 'APPROVED',
    actedByRole: 'FINANCE',
    actedByName: 'Sri Wahyuni, S.E.',
    timestamp: '2026-08-18 14:00',
    notes: 'Pencairan kasbon Rp 1.500.000 disetujui dan ditransfer via Mandiri.',
  },
];

export const INITIAL_VENDORS: Vendor[] = [
  {
    id: 'vendor-ta',
    name: 'Telkom / Telkom Akses (TA)',
    code: 'TELKOM',
    scopeType: 'END_TO_END',
    picName: 'Pak Budi Hartono (Regional CJ)',
    phone: '0812-1111-2222',
    email: 'vendor.telkom@example.com',
    notes: 'Scope: End-to-End (Perizinan RT/RW & Dinas PUPR + Penarikan + Tiang + Splicing)',
  },
  {
    id: 'vendor-fs',
    name: 'FiberStar (FS)',
    code: 'FIBERSTAR',
    scopeType: 'IMPLEMENTATION_ONLY',
    picName: 'Ibu Ratna Dewi (Project Manager)',
    phone: '0813-3333-4444',
    email: 'project.fs@example.com',
    notes: 'Scope: Implementation Only (Perizinan diurus langsung oleh FiberStar)',
  },
  {
    id: 'vendor-mr',
    name: 'MyRepublic / Moratelindo',
    code: 'MYREP',
    scopeType: 'END_TO_END',
    picName: 'Pak Hendra Kurniawan',
    phone: '0815-5555-6666',
    email: 'rollout.myrep@example.com',
    notes: 'Scope: End-to-End (Turnkey Cluster Rollout)',
  },
];

export const INITIAL_MANDORS: Mandor[] = [
  {
    id: 'mandor-1',
    name: 'Mandor ADW Mandiri (Pak Fatrah)',
    phone: '0812-7777-8888',
    teamSize: 12,
    specialization: 'All-in-One',
    area: 'Pemalang, Pekalongan, Batang',
    bankName: 'BCA',
    accountNumber: '891-034-5678',
    accountHolder: 'FATRAH SUBARKAH',
    outstandingKasbon: 1500000,
    notes: 'Mandor utama untuk Cluster Pemalang',
  },
  {
    id: 'mandor-2',
    name: 'Mandor Pak Sugeng & Tim',
    phone: '0813-9999-0000',
    teamSize: 8,
    specialization: 'Tarik Kabel FO',
    area: 'Tegal, Slawi, Brebes',
    bankName: 'MANDIRI',
    accountNumber: '137-00-1234567-8',
    accountHolder: 'SUGENG RIYADI',
    outstandingKasbon: 0,
    notes: 'Spesialis penarikan kabel distribusi & feeder jarak jauh',
  },
  {
    id: 'mandor-3',
    name: 'Mandor Pak Wahyu Splicer',
    phone: '0811-3333-7777',
    teamSize: 4,
    specialization: 'Splicing & OTDR',
    area: 'Jawa Tengah All Area',
    bankName: 'BRI',
    accountNumber: '0123-01-004567-53-1',
    accountHolder: 'WAHYU HIDAYAT',
    outstandingKasbon: 500000,
    notes: 'Spesialis splicing FAT, FDT, ODC, dan uji OPM/OTDR',
  },
  {
    id: 'mandor-4',
    name: 'Mandor Pak Rahmat Pantura',
    phone: '0852-4444-8888',
    teamSize: 6,
    specialization: 'Sipil Tiang',
    area: 'Pantura Barat',
    bankName: 'BNI',
    accountNumber: '089-123-4567',
    accountHolder: 'RAHMAT HIDAYATULLAH',
    outstandingKasbon: 0,
    notes: 'Spesialis tanam tiang 7m/9m dan perintisan jalur',
  },
];

export const INITIAL_PAYMENT_REQUESTS: MandorPaymentRequest[] = [
  {
    id: 'req-001',
    requestNo: 'REQ-OPS/2026/08/001',
    spkId: 'spk-pemalang',
    clusterName: 'CLUSTER PEMALANG',
    siteId: 'site-pemalang-ds',
    siteName: 'PULLING DISTRIBUSI DUSUN MANGUNSARI TEGALSARI BARAT PEMALANG',
    mandorId: 'mandor-1',
    mandorName: 'Mandor ADW Mandiri (Pak Fatrah)',
    bankName: 'BCA',
    accountNumber: '891-034-5678',
    accountHolder: 'FATRAH SUBARKAH',
    type: 'TERMIN',
    termNumber: 1,
    requestedAmount: 4800000,
    deductedKasbon: 0,
    netTransferAmount: 4800000,
    verifiedProgressPercent: 52.42,
    reason: 'Pengajuan Termin 1 (DP 30% Jasa Mandor) - Mobilisasi & penarikan FO 2.440 meter telah selesai diverifikasi',
    submittedBy: 'Usep Kurnia (Project Control)',
    submittedAt: '2026-08-15',
    approvedBy: 'Teguh Prayoga (Project Manager)',
    approvedAt: '2026-08-15',
    paidAt: '2026-08-15',
    transferRef: 'TRF-BCA-89230198',
    status: 'PAID',
    financeNotes: 'Telah ditransfer via KlikBCA Bisnis ke rekening BCA Fatrah Subarkah',
  },
  {
    id: 'req-002',
    requestNo: 'REQ-OPS/2026/08/002',
    spkId: 'spk-pemalang',
    clusterName: 'CLUSTER PEMALANG',
    siteId: 'site-pemalang-ds',
    siteName: 'PULLING DISTRIBUSI DUSUN MANGUNSARI TEGALSARI BARAT PEMALANG',
    mandorId: 'mandor-1',
    mandorName: 'Mandor ADW Mandiri (Pak Fatrah)',
    bankName: 'BCA',
    accountNumber: '891-034-5678',
    accountHolder: 'FATRAH SUBARKAH',
    type: 'KASBON',
    requestedAmount: 1500000,
    deductedKasbon: 0,
    netTransferAmount: 1500000,
    verifiedProgressPercent: 52.42,
    reason: 'Kasbon Operasional Mandor untuk tambahan regu penanaman tiang 3 inch di area Mangunsari',
    submittedBy: 'Usep Kurnia (Project Control)',
    submittedAt: '2026-08-18',
    approvedBy: 'Teguh Prayoga (Project Manager)',
    approvedAt: '2026-08-19',
    paidAt: '2026-08-19',
    transferRef: 'TRF-BCA-99120034',
    status: 'PAID',
    financeNotes: 'Kasbon operasional disetujui, akan dipotongkan pada Termin 2 Mandor',
  },
  {
    id: 'req-003',
    requestNo: 'REQ-OPS/2026/08/003',
    spkId: 'spk-tegal-slawi',
    clusterName: 'CLUSTER TEGAL SLAWI',
    siteId: 'site-tegal-1',
    siteName: 'PULLING DISTRIBUSI AREA SLAWI KULON',
    mandorId: 'mandor-2',
    mandorName: 'Mandor Pak Sugeng & Tim',
    bankName: 'MANDIRI',
    accountNumber: '137-00-1234567-8',
    accountHolder: 'SUGENG RIYADI',
    type: 'TERMIN',
    termNumber: 1,
    requestedAmount: 7200000,
    deductedKasbon: 0,
    netTransferAmount: 7200000,
    verifiedProgressPercent: 65.0,
    reason: 'Pengajuan Termin 1 (DP 30% Jasa) Slawi Kulon - Penarikan 3.500m kabel selesai',
    submittedBy: 'Fatrah Subarkah (Estimator)',
    submittedAt: '2026-08-10',
    approvedBy: 'Teguh Prayoga (PM)',
    approvedAt: '2026-08-10',
    paidAt: '2026-08-10',
    transferRef: 'TRF-MDR-44556677',
    status: 'PAID',
    financeNotes: 'Lunas ditransfer',
  },
];

export const INITIAL_DAILY_REPORTS: import('@/types').DailyProgressReport[] = [
  {
    id: 'dpr-001',
    spkId: 'spk-pemalang',
    clusterName: 'CLUSTER PEMALANG',
    siteId: 'site-pemalang-ds',
    siteName: 'PULLING DISTRIBUSI DUSUN MANGUNSARI TEGALSARI BARAT PEMALANG',
    vendorName: 'Telkom / Telkom Akses (TA)',
    date: '2026-08-24',
    dayName: 'Senin',
    startImDate: '2026-08-11',
    mitraName: 'PT Indotek Buana Karya',
    mandorName: 'Mandor ADW Mandiri (Pak Fatrah)',
    teamSize: 12,
    jointerName: 'Wahyu Splicer',
    overallProgressPercent: 52.42,
    photos: [
      {
        id: 'ph-1',
        url: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=600&q=80',
        caption: 'Penanaman Tiang 7m 3 inch di Gang 3 Dusun Mangunsari',
        category: 'TIANG',
        timestamp: '2026-08-24 10:15 WIB',
      },
      {
        id: 'ph-2',
        url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
        caption: 'Penarikan Kabel FO ADSS 48 core jalur distribusi RW 04',
        category: 'PENARIKAN_FO',
        timestamp: '2026-08-24 14:30 WIB',
      },
    ],
    items: [
      { id: 'di-1', category: 'CABLE', itemName: 'Pulling Kabel FO 48c', unit: 'Meter', planQty: 2440, todayQty: 440, totalActualQty: 2440, status: 'DONE' },
      { id: 'di-2', category: 'CIVIL_DIGGING', itemName: 'Digging Hole / Gali Lubang', unit: 'Titik', planQty: 54, todayQty: 8, totalActualQty: 54, status: 'DONE' },
      { id: 'di-3', category: 'POLE', itemName: 'Tanam Tiang 7m 4"', unit: 'Set', planQty: 1, todayQty: 0, totalActualQty: 0, status: 'PENDING' },
      { id: 'di-4', category: 'POLE', itemName: 'Tanam Tiang 7m 3"', unit: 'Set', planQty: 44, todayQty: 6, totalActualQty: 48, status: 'DONE' },
      { id: 'di-5', category: 'POLE', itemName: 'Tanam Tiang 7m 2.5"', unit: 'Set', planQty: 9, todayQty: 2, totalActualQty: 6, status: 'IN_PROGRESS' },
      { id: 'di-6', category: 'FAT_FDT', itemName: 'Install Pole Mounted FAT (16 port)', unit: 'Unit', planQty: 19, todayQty: 0, totalActualQty: 0, status: 'PENDING' },
      { id: 'di-7', category: 'FAT_FDT', itemName: 'Install 48c Pole Mounted FDT', unit: 'Set', planQty: 1, todayQty: 0, totalActualQty: 0, status: 'PENDING' },
      { id: 'di-8', category: 'ACCESSORIES', itemName: 'Dead End Fittings / Clamp Buaya', unit: 'Pcs', planQty: 90, todayQty: 15, totalActualQty: 99, status: 'DONE' },
      { id: 'di-9', category: 'ACCESSORIES', itemName: 'Suspension Clamp', unit: 'Pcs', planQty: 9, todayQty: 0, totalActualQty: 9, status: 'DONE' },
      { id: 'di-10', category: 'ACCESSORIES', itemName: 'Pole Clamp Single', unit: 'Pcs', planQty: 45, todayQty: 8, totalActualQty: 48, status: 'DONE' },
      { id: 'di-11', category: 'ACCESSORIES', itemName: 'Cable Loop Holder / Plat Strip', unit: 'Set', planQty: 20, todayQty: 5, totalActualQty: 20, status: 'DONE' },
      { id: 'di-12', category: 'ACCESSORIES', itemName: 'Strand Wire / Sling Messenger 6mm', unit: 'Meter', planQty: 781, todayQty: 120, totalActualQty: 300, status: 'IN_PROGRESS' },
    ],
    activitiesToday: [
      'Penarikan sisa kabel FO 48 core di jalur Mangunsari RW 04',
      'Tanam tiang 7m 3 inch sebanyak 6 batang',
      'Pemasangan dead end clamp & cable loop hanger',
    ],
    planTomorrow: [
      'Instalasi FAT 16 ports pada tiang terpasang',
      'Pemasangan strand wire sling messenger',
      'Persiapan tim splicing',
    ],
    issues: [
      'Cuaca hujan gerimis di sore hari (pukul 15:30 WIB)',
      'Perintisan dahan pohon di gang sebelah barat',
    ],
    weather: 'Cerah Berawan / Hujan Sore',
    submittedBy: 'Usep Kurnia (Field Supervisor / QC)',
    createdAt: '2026-08-24 17:30',
  },
  {
    id: 'dpr-002',
    spkId: 'spk-tegal-slawi',
    clusterName: 'CLUSTER KELURAHAN GUNUNG TAWANG WONOSOBO',
    siteId: 'site-tegal-1',
    siteName: 'FTTH MYREPUBLIC + JAWA TENGAH',
    vendorName: 'MyRepublic / Moratelindo',
    date: '2026-08-24',
    dayName: 'Senin',
    startImDate: 'Selasa, 18/08/2026',
    mitraName: 'PT Indotek Buana Karya (Indotex)',
    mandorName: 'Mandor Widodo',
    teamSize: 5,
    jointerName: 'Jointer Tim A',
    overallProgressPercent: 68.5,
    photos: [
      {
        id: 'ph-3',
        url: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=600&q=80',
        caption: 'Pemasangan Tiang & Dead End Clamp di Jalur Line A',
        category: 'TIANG',
        timestamp: '2026-08-24 11:00 WIB',
      },
    ],
    items: [
      { id: 'gw-1', category: 'CABLE', itemName: 'Pulling Kabel 24c (Total)', unit: 'Meter', planQty: 1838, todayQty: 0, totalActualQty: 1860, status: 'DONE' },
      { id: 'gw-2', category: 'CABLE', itemName: 'Line A 24c', unit: 'Meter', planQty: 1019, todayQty: 0, totalActualQty: 1030, status: 'DONE' },
      { id: 'gw-3', category: 'CABLE', itemName: 'Line B 24c', unit: 'Meter', planQty: 819, todayQty: 0, totalActualQty: 830, status: 'DONE' },
      { id: 'gw-4', category: 'CIVIL_DIGGING', itemName: 'Digging Hole / Gali Lubang', unit: 'Titik', planQty: 34, todayQty: 0, totalActualQty: 31, status: 'IN_PROGRESS' },
      { id: 'gw-5', category: 'POLE', itemName: 'Tanam Tiang 7m 4"', unit: 'Set', planQty: 0, todayQty: 0, totalActualQty: 0, status: 'DONE' },
      { id: 'gw-6', category: 'POLE', itemName: 'Tanam Tiang 7m 3"', unit: 'Set', planQty: 34, todayQty: 0, totalActualQty: 31, status: 'IN_PROGRESS' },
      { id: 'gw-7', category: 'POLE', itemName: 'Tanam Tiang 7m 2.5"', unit: 'Set', planQty: 0, todayQty: 0, totalActualQty: 0, status: 'DONE' },
      { id: 'gw-8', category: 'FAT_FDT', itemName: 'FDT 48c', unit: 'Set', planQty: 1, todayQty: 1, totalActualQty: 1, status: 'DONE' },
      { id: 'gw-9', category: 'FAT_FDT', itemName: 'FAT Total', unit: 'Unit', planQty: 15, todayQty: 4, totalActualQty: 4, status: 'IN_PROGRESS' },
      { id: 'gw-10', category: 'FAT_FDT', itemName: 'FAT Line A', unit: 'Unit', planQty: 9, todayQty: 4, totalActualQty: 5, status: 'IN_PROGRESS' },
      { id: 'gw-11', category: 'FAT_FDT', itemName: 'FAT Line B', unit: 'Unit', planQty: 6, todayQty: 0, totalActualQty: 0, status: 'PENDING' },
      { id: 'gw-12', category: 'ACCESSORIES', itemName: 'Dead End', unit: 'Pcs', planQty: 48, todayQty: 12, totalActualQty: 48, status: 'DONE' },
      { id: 'gw-13', category: 'ACCESSORIES', itemName: 'Suspension', unit: 'Pcs', planQty: 10, todayQty: 2, totalActualQty: 10, status: 'DONE' },
      { id: 'gw-14', category: 'ACCESSORIES', itemName: 'Clamp Pole', unit: 'Pcs', planQty: 37, todayQty: 5, totalActualQty: 37, status: 'DONE' },
      { id: 'gw-15', category: 'ACCESSORIES', itemName: 'Slack Hanger', unit: 'Pcs', planQty: 16, todayQty: 4, totalActualQty: 16, status: 'DONE' },
      { id: 'gw-16', category: 'CIVIL_DIGGING', itemName: 'SF Digging', unit: 'Titik', planQty: 50, todayQty: 2, totalActualQty: 32, status: 'IN_PROGRESS' },
      { id: 'gw-17', category: 'POLE', itemName: 'SF Tanam Tiang 7m 4"', unit: 'Set', planQty: 42, todayQty: 12, totalActualQty: 32, status: 'IN_PROGRESS' },
      { id: 'gw-18', category: 'POLE', itemName: 'SF Tanam Tiang 9m 4"', unit: 'Set', planQty: 8, todayQty: 0, totalActualQty: 0, status: 'PENDING' },
      { id: 'gw-19', category: 'CABLE', itemName: 'SF Kabel 48c', unit: 'Meter', planQty: 3059, todayQty: 0, totalActualQty: 0, status: 'PENDING' },
      { id: 'gw-20', category: 'FAT_FDT', itemName: 'SF JC 144', unit: 'Unit', planQty: 1, todayQty: 0, totalActualQty: 0, status: 'PENDING' },
    ],
    activitiesToday: [
      'Tanam tiang',
      'Install aksesoris (dead end, clamp pole, slack hanger)',
    ],
    planTomorrow: [
      'Tanam tiang lanjutan',
      'Install FAT',
      'Install aksesoris lanjutan',
    ],
    issues: [
      'Nihil (Aman terkendali)',
    ],
    weather: 'Cerah',
    submittedBy: 'Field Supervisor Wonosobo',
    createdAt: '2026-08-24 18:00',
  },
  {
    id: 'dpr-003',
    spkId: 'spk-pekalongan-utara',
    clusterName: 'KELURAHAN SUKAPERNA MAJALENGKA',
    siteId: 'site-pkl-1',
    siteName: 'SITE 1: KELURAHAN SUKAPERNA MAJALENGKA',
    vendorName: 'FiberStar (FS)',
    date: '2026-08-12',
    dayName: 'Rabu',
    startImDate: '2026-08-01',
    mitraName: 'PT Indotek Buana Karya',
    mandorName: 'Mandor Pak Sugeng & Tim',
    teamSize: 8,
    overallProgressPercent: 24.5,
    photos: [
      {
        id: 'ph-4',
        url: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=600&q=80',
        caption: 'Gali Lubang & Tanam Tiang 7m 3 inch Sukaperna',
        category: 'TIANG',
        timestamp: '2026-08-12 15:00 WIB',
      },
    ],
    items: [
      { id: 'sk-1', category: 'POLE', itemName: 'Pole 7m 4"', unit: 'Set', planQty: 1, todayQty: 0, totalActualQty: 0, status: 'PENDING' },
      { id: 'sk-2', category: 'POLE', itemName: 'Pole 7m 3"', unit: 'Set', planQty: 44, todayQty: 17, totalActualQty: 17, status: 'IN_PROGRESS' },
      { id: 'sk-3', category: 'POLE', itemName: 'Pole 7m 2.5"', unit: 'Set', planQty: 28, todayQty: 3, totalActualQty: 3, status: 'IN_PROGRESS' },
      { id: 'sk-4', category: 'CABLE', itemName: 'Cable ADSS 24c', unit: 'Meter', planQty: 3655, todayQty: 0, totalActualQty: 0, status: 'PENDING' },
      { id: 'sk-5', category: 'FAT_FDT', itemName: 'Install FAT', unit: 'Unit', planQty: 25, todayQty: 0, totalActualQty: 0, status: 'PENDING' },
      { id: 'sk-6', category: 'FAT_FDT', itemName: 'Install FDT', unit: 'Set', planQty: 1, todayQty: 0, totalActualQty: 0, status: 'PENDING' },
      { id: 'sk-7', category: 'CIVIL_DIGGING', itemName: 'Digging', unit: 'Titik', planQty: 73, todayQty: 24, totalActualQty: 24, status: 'IN_PROGRESS' },
    ],
    activitiesToday: [
      'Digging + Instal Pole',
    ],
    planTomorrow: [
      'Lanjutan digging lubang & penanaman tiang',
    ],
    issues: [
      'Jalur tanah berbatu pada titik gang utara',
    ],
    weather: 'Cerah',
    submittedBy: 'Koordinator Lapangan Majalengka',
    createdAt: '2026-08-12 17:00',
  },
];

export const INITIAL_MATERIAL_POS: import('@/types').MaterialPurchaseOrder[] = [
  {
    id: 'po-mat-001',
    poNumber: 'PO-MAT/IBK/2026/08/001',
    spkId: 'spk-pemalang',
    clusterName: 'CLUSTER PEMALANG',
    siteId: 'site-pemalang-ds',
    siteName: 'PULLING DISTRIBUSI DUSUN MANGUNSARI TEGALSARI BARAT PEMALANG',
    supplierName: 'CV Surya Aksesoris Optik Semarang',
    supplierContact: 'Pak Hendra (0812-3456-7890)',
    supplierBankName: 'BCA',
    supplierBankAccount: '8090-1122-33',
    supplierBankHolder: 'CV Surya Aksesoris Optik',
    purchaseDate: '2026-08-14',
    paymentMethod: 'TRANSFER_SUPPLIER',
    totalAmount: 3845000,
    status: 'RECEIVED_GUDANG',
    deliveryOrderNo: 'DO-SAO-8821',
    receiptPhotoUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=600&q=80',
    requestedBy: 'Budhimansyah (Commercial / Procurement)',
    requestedAt: '2026-08-13 14:00',
    approvedBy: 'Teguh Prayoga (PM)',
    approvedAt: '2026-08-13 16:30',
    paidAt: '2026-08-14 09:15',
    transferRef: 'TRF-BCA-889123',
    notes: 'Pembelian aksesoris dead end, klem tiang, dan strand wire untuk pemenuhan SOW Distribusi Pemalang',
    items: [
      { id: 'poi-1', materialName: 'Clamps Dead end Fittings/clamp buaya', category: 'ACCESSORIES', uom: 'Pcs', qty: 90, unitPrice: 10500, totalPrice: 945000, notes: 'Harga grosir supplier' },
      { id: 'poi-2', materialName: 'Pole clamp single', category: 'FASTENERS', uom: 'Pcs', qty: 45, unitPrice: 10000, totalPrice: 450000, notes: 'Klem tiang 3 inch' },
      { id: 'poi-3', materialName: 'Strand Wire Messenger 6 mm', category: 'ACCESSORIES', uom: 'Meter', qty: 300, unitPrice: 4500, totalPrice: 1350000, notes: 'Sling messenger kawat baja' },
      { id: 'poi-4', materialName: 'Cable loop holder/plat strip/Cable hanger', category: 'FASTENERS', uom: 'Set', qty: 20, unitPrice: 55000, totalPrice: 1100000, notes: 'Plat strip gantungan kabel' },
    ],
  },
  {
    id: 'po-mat-002',
    poNumber: 'PO-MAT/IBK/2026/08/002',
    spkId: 'spk-tegal-slawi',
    clusterName: 'CLUSTER TEGAL SLAWI',
    siteId: 'site-tegal-1',
    siteName: 'FTTH MYREPUBLIC + JAWA TENGAH',
    supplierName: 'Toko Bintang Fiber Tegal',
    supplierContact: 'Ibu Ratna (0856-7890-1234)',
    supplierBankName: 'Mandiri',
    supplierBankAccount: '138-00-998877-6',
    supplierBankHolder: 'Toko Bintang Fiber',
    purchaseDate: '2026-08-20',
    paymentMethod: 'TRANSFER_SUPPLIER',
    totalAmount: 2150000,
    status: 'PAID',
    receiptPhotoUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=600&q=80',
    requestedBy: 'Budhimansyah (Commercial / Procurement)',
    requestedAt: '2026-08-19 11:00',
    approvedBy: 'Teguh Prayoga (PM)',
    approvedAt: '2026-08-19 15:00',
    paidAt: '2026-08-20 10:00',
    transferRef: 'TRF-MDR-99014',
    notes: 'Belanja aksesoris dead end, suspension clamp, slack hanger untuk cluster Gunung Tawang',
    items: [
      { id: 'poi-5', materialName: 'Dead End Fittings', category: 'ACCESSORIES', uom: 'Pcs', qty: 48, unitPrice: 11000, totalPrice: 528000 },
      { id: 'poi-6', materialName: 'Suspension Clamp', category: 'ACCESSORIES', uom: 'Pcs', qty: 10, unitPrice: 12500, totalPrice: 125000 },
      { id: 'poi-7', materialName: 'Clamp Pole', category: 'FASTENERS', uom: 'Pcs', qty: 37, unitPrice: 10500, totalPrice: 388500 },
      { id: 'poi-8', materialName: 'Slack Hanger', category: 'ACCESSORIES', uom: 'Pcs', qty: 16, unitPrice: 69281, totalPrice: 1108500 },
    ],
  },
];

export const INITIAL_MATERIAL_HANDOVERS: import('@/types').MaterialHandover[] = [
  {
    id: 'sj-001',
    suratJalanNo: 'SJ-MAT/IBK/2026/08/001',
    spkId: 'spk-pemalang',
    clusterName: 'CLUSTER PEMALANG',
    siteId: 'site-pemalang-ds',
    siteName: 'PULLING DISTRIBUSI DUSUN MANGUNSARI TEGALSARI BARAT PEMALANG',
    mandorId: 'mandor-1',
    mandorName: 'Mandor ADW Mandiri (Pak Fatrah)',
    handoverDate: '2026-08-16',
    receiverName: 'Wahyu (Leader Tim Mandor ADW)',
    deliveredBy: 'Agus Santoso (Logistik & Gudang IBK)',
    status: 'ACKNOWLEDGED',
    notes: 'Serah terima aksesoris tahap 1 untuk pengerjaan jalur RW 04 & RW 05',
    items: [
      { id: 'sji-1', materialName: 'Clamps Dead end Fittings/clamp buaya', uom: 'Pcs', qty: 90, notes: 'Lengkap' },
      { id: 'sji-2', materialName: 'Pole clamp single', uom: 'Pcs', qty: 45, notes: 'Lengkap' },
      { id: 'sji-3', materialName: 'Strand Wire Messenger 6 mm', uom: 'Meter', qty: 300, notes: 'Kawat baja galvanis' },
      { id: 'sji-4', materialName: 'Cable loop holder/plat strip', uom: 'Set', qty: 20, notes: 'Lengkap' },
    ],
  },
];

export const INITIAL_SUPPLIERS: import('@/types').Supplier[] = [
  {
    id: 'sup-1',
    name: 'CV Surya Aksesoris Optik',
    category: 'AKSESORIS_FO',
    city: 'Semarang, Jawa Tengah',
    picName: 'Pak Hendra (Sales Manager)',
    phone: '0812-3456-7890',
    email: 'surya.aksesoris@optik.co.id',
    bankName: 'BCA',
    accountNumber: '8090-1122-33',
    accountHolder: 'CV Surya Aksesoris Optik',
    notes: 'Supplier utama Dead End clamp, Suspension clamp, dan Slack hanger.',
  },
  {
    id: 'sup-2',
    name: 'Toko Bintang Fiber Tegal',
    category: 'AKSESORIS_FO',
    city: 'Tegal, Jawa Tengah',
    picName: 'Ibu Ratna Dewi',
    phone: '0856-7890-1234',
    email: 'bintangfiber.tegal@gmail.com',
    bankName: 'MANDIRI',
    accountNumber: '138-00-998877-6',
    accountHolder: 'Toko Bintang Fiber',
    notes: 'Penyedia aksesoris klem tiang, belt plate, dan bulldog grip.',
  },
  {
    id: 'sup-3',
    name: 'PT Baja Presisi Tiangindo',
    category: 'TIANG_DAN_BESI',
    city: 'Cirebon, Jawa Barat',
    picName: 'Pak Wahyudi',
    phone: '0819-2233-4455',
    email: 'sales@bajapresisi.com',
    bankName: 'BNI',
    accountNumber: '022-8877-665',
    accountHolder: 'PT Baja Presisi Tiangindo',
    notes: 'Fabrikasi Tiang 7m 3", 7m 4", dan 9m standar Telkom / STEL.',
  },
  {
    id: 'sup-4',
    name: 'CV Prima Fiberindo Surabaya',
    category: 'KABEL_DAN_FIBER',
    city: 'Surabaya, Jawa Timur',
    picName: 'Pak David Prasetyo',
    phone: '0821-4455-6677',
    email: 'order@primafiber.id',
    bankName: 'BCA',
    accountNumber: '018-9900-112',
    accountHolder: 'CV Prima Fiberindo',
    notes: 'Distributor Kabel FO ADSS 24c/48c, FAT 16 port, dan FDT.',
  },
];

export const INITIAL_PRICE_CATALOG: PriceCatalogItem[] = [
  { id: 'cat-1', name: 'Bulldog grip', category: 'MATERIAL', unit: 'Pcs', estimatedQty: 500, referencePrice: 3000, notes: 'Penjepit sling messenger' },
  { id: 'cat-2', name: 'Cable loop holder/plat strip/Cable hanger', category: 'MATERIAL', unit: 'Set', estimatedQty: 250, referencePrice: 56000, notes: 'Plat strip gantungan kabel' },
  { id: 'cat-3', name: 'Clamps Dead end Fittings/clamp buaya', category: 'MATERIAL', unit: 'Pcs', estimatedQty: 750, referencePrice: 13000, notes: 'Klem dead end FO 24c/48c' },
  { id: 'cat-4', name: 'Label Cable (on pole, in Handhole)', category: 'MATERIAL', unit: 'Pcs', estimatedQty: 250, referencePrice: 7500, notes: 'Label tanda kabel vendor' },
  { id: 'cat-5', name: 'Label FAT (include QR Code)', category: 'MATERIAL', unit: 'Pcs', estimatedQty: 100, referencePrice: 7500, notes: 'Label FAT QR Code' },
  { id: 'cat-6', name: 'Label FDT', category: 'MATERIAL', unit: 'Pcs', estimatedQty: 100, referencePrice: 7500, notes: 'Label FDT' },
  { id: 'cat-7', name: 'Label Pole', category: 'MATERIAL', unit: 'Pcs', estimatedQty: 500, referencePrice: 5000, notes: 'Label nomor tiang' },
  { id: 'cat-8', name: 'Plate belt 20mm', category: 'MATERIAL', unit: 'Pcs', estimatedQty: 500, referencePrice: 4300, notes: 'Sabuk plat stainless steel' },
  { id: 'cat-9', name: 'Pole clamp single', category: 'MATERIAL', unit: 'Pcs', estimatedQty: 500, referencePrice: 12000, notes: 'Klem tiang single 3 inch' },
  { id: 'cat-10', name: 'Steel clamp', category: 'MATERIAL', unit: 'Pcs', estimatedQty: 100, referencePrice: 7000, notes: 'Klem baja' },
  { id: 'cat-11', name: 'Suspension clamp', category: 'MATERIAL', unit: 'Pcs', estimatedQty: 150, referencePrice: 13500, notes: 'Klem gantung suspension' },
  { id: 'cat-12', name: 'Strand Wire Messenger 6 mm', category: 'MATERIAL', unit: 'Meter', estimatedQty: 2000, referencePrice: 4850, notes: 'Kawat baja sling 6mm' },
  { id: 'cat-13', name: 'Jasa Penarikan Kabel FO 24c/48c', category: 'JASA_MANDOR', unit: 'Meter', estimatedQty: 5000, referencePrice: 2100, notes: 'Harga standar jasa tarik mandor' },
  { id: 'cat-14', name: 'Jasa Pemasangan Tiang 7m (Gali & Cor)', category: 'JASA_MANDOR', unit: 'Set', estimatedQty: 100, referencePrice: 110000, notes: 'Standar jasa tanam tiang 7m' },
  { id: 'cat-15', name: 'Jasa Splicing Core & OTDR', category: 'JASA_MANDOR', unit: 'Core', estimatedQty: 200, referencePrice: 20000, notes: 'Splicing per core + test OPM' },
  { id: 'cat-16', name: 'Jasa Instalasi FAT / FDT', category: 'JASA_MANDOR', unit: 'Unit', estimatedQty: 50, referencePrice: 35000, notes: 'Pemasangan FAT pada tiang' },
];

export const INITIAL_SPKS: SPK[] = [
  {
    id: 'spk-pemalang',
    vendorId: 'vendor-ta',
    vendorName: 'Telkom / Telkom Akses (TA)',
    scopeType: 'END_TO_END',
    workflowStage: 'PELAKSANAAN',
    spkNumber: 'SPK 3 & 4/PT INDOTEK BUANA KARYA/TSN - FTTH TurnKey EMR CJ 2026/ATE/VIII/2026',
    clusterName: 'CLUSTER PEMALANG',
    region: 'Central Java',
    status: 'Approved',
    createdAt: '2026-08-11',
    targetCompletionDate: '2026-09-15',
    notes: [
      '1. SPK 04 > Perlu dicek ulang apakah SOW actualnya DS RW06 / DS RW05 (filename & isi spk berbeda)',
      '2. Harga Material > perlu harga actual pasar agar persentase yang muncul bisa mendekati dengan apa yang diharapkan',
      '3. Jika melihat margin, secara keseluruhan mendapat 29,72%, namun jika melihat secara cluster ada beberapa yang perlu direview kembali',
    ],
    revisionLogs: [
      {
        id: 'rev-1',
        version: 'v1',
        date: '2026-08-11',
        author: 'Fatrah Subarkah (Estimator)',
        status: 'Done',
        note: 'Initial SPK breakdown dari PO Telkom & alokasi harga ke Mandor',
      },
      {
        id: 'rev-2',
        version: 'v2',
        date: '2026-08-17',
        author: 'Teguh Prayoga (PM)',
        status: 'Revisi',
        note: 'Ada penurunan Margin dari yang sebelumnya 27% menjadi 25%',
      },
      {
        id: 'rev-3',
        version: 'v3',
        date: '2026-08-18',
        author: 'Budhimansyah (Commercial)',
        status: 'Penawaran',
        note: 'Standar harga untuk mandor sudah di update, jika ada penawaran silahkan mengajukan harga negosiasi bukan merubah harga per item',
      },
      {
        id: 'rev-4',
        version: 'v4',
        date: '2026-08-19',
        author: 'Fatrah & Budhimansyah',
        status: 'OK',
        note: 'STATUS: OK (19/08/2026) - SPK Mandor dirilis & pekerjaan lapangan dimulai',
      },
    ],
    signOffs: [
      { role: 'Estimator', name: 'Fatrah Subarkah', date: '2026-08-11', status: 'Done' },
      { role: 'Project Control', name: 'Usep Kurnia', date: '2026-08-15', status: 'Reviewed' },
      { role: 'Commercial / Procurement', name: 'Budhimansyah', date: '2026-08-18', status: 'Penawaran' },
      { role: 'Management / Approval', name: 'Teguh Prayoga', date: '2026-08-19', status: 'Approved' },
    ],
    sites: [
      {
        id: 'site-pemalang-ds',
        spkId: 'spk-pemalang',
        name: 'PULLING DISTRIBUSI DUSUN MANGUNSARI TEGALSARI BARAT PEMALANG',
        sowType: 'Distribusi',
        poAmount: 34125800,
        mandorId: 'mandor-1',
        mandorName: 'Mandor ADW Mandiri (Pak Fatrah)',
        paymentTerms: [
          { id: 'term-ds-1', siteId: 'site-pemalang-ds', termNumber: 1, percentage: 30, amount: 4800000, isPaid: true, paidDate: '2026-08-15', note: 'Termin 1 Mandor (30% Jasa DP)' },
          { id: 'term-ds-2', siteId: 'site-pemalang-ds', termNumber: 2, percentage: 40, amount: 6400000, isPaid: false, note: 'Termin 2 Mandor (40% saat progres 70%)' },
          { id: 'term-ds-3', siteId: 'site-pemalang-ds', termNumber: 3, percentage: 30, amount: 4800000, isPaid: false, note: 'Termin 3 Mandor (Pelunasan 100% BAST)' },
        ],
        permitItems: [
          {
            id: 'p-ds-1',
            siteId: 'site-pemalang-ds',
            name: 'Izin Koordinasi RT/RW Dusun Mangunsari Tegalsari',
            category: 'Lingkungan / Warga',
            estimatedCost: 0,
            actualCost: 0,
            status: 'Approved / Selesai',
            pic: 'Pak Usep Kurnia',
            notes: 'Koordinasi warga klir, diizinkan tanam tiang',
          },
        ],
        services: [
          { id: 'j-ds-1', siteId: 'site-pemalang-ds', name: 'FO core type SM G.652.D-ADSS 48 cores', qty: 2440, uom: 'Meter', unitPrice: 2100, remark: 'Include Pemasangan Label Kabel', actualProgress: 2440 },
          { id: 'j-ds-2', siteId: 'site-pemalang-ds', name: 'Pemasangan Tiang 7 meter 4", STEL L-003 1996', qty: 1, uom: 'Set', unitPrice: 110000, remark: 'Include Pemasangan Pole Clamp Single & Label Tihang', actualProgress: 0 },
          { id: 'j-ds-3', siteId: 'site-pemalang-ds', name: 'Pemasangan Tiang 7 meter 3 inch', qty: 44, uom: 'Set', unitPrice: 105000, remark: 'Include Pemasangan Pole Clamp Single & Label Tihang', actualProgress: 48 },
          { id: 'j-ds-4', siteId: 'site-pemalang-ds', name: 'Pemasangan Tiang 7 meter 2,5 inch', qty: 9, uom: 'Set', unitPrice: 100000, remark: 'Include Pemasangan Pole Clamp Single & Label Tihang', actualProgress: 6 },
          { id: 'j-ds-5', siteId: 'site-pemalang-ds', name: 'Instal Pole mounted outdoor type (16 ports type) Include OPM OTDR', qty: 19, uom: 'Unit', unitPrice: 100000, remark: 'Include Pemasangan Label FAT', actualProgress: 0 },
          { id: 'j-ds-6', siteId: 'site-pemalang-ds', name: 'Instal 48 cores capacity pole mounted FDT', qty: 1, uom: 'Set', unitPrice: 30000, remark: 'Include Pemasangan Label FDT', actualProgress: 0 },
          { id: 'j-ds-7', siteId: 'site-pemalang-ds', name: 'Cable loop holder/plat strip/Cable hanger', qty: 20, uom: 'Set', unitPrice: 5000, remark: 'Include Pemasangan Plate Belt', actualProgress: 20 },
          { id: 'j-ds-8', siteId: 'site-pemalang-ds', name: 'Instalasi strand wire/sling messenger 6 mm', qty: 781, uom: 'Meter', unitPrice: 2000, remark: 'Include Pemasangan Buldog Grip', actualProgress: 300 },
          { id: 'j-ds-9', siteId: 'site-pemalang-ds', name: 'Clamps Dead End Fittings/clamp buaya', qty: 90, uom: 'Pcs', unitPrice: 2000, remark: 'Include Pemasangan Suspension Clamp', actualProgress: 99 },
          { id: 'j-ds-10', siteId: 'site-pemalang-ds', name: 'Splicing', qty: 38, uom: 'Core', unitPrice: 20000, remark: '', actualProgress: 0 },
          { id: 'j-ds-11', siteId: 'site-pemalang-ds', name: 'Negosiasi Mitra', qty: 1, uom: 'Lot', unitPrice: 714000, remark: 'Financial lump-sum adjustment', actualProgress: 1, isNegosiasi: true },
        ],
        materials: [
          { id: 'm-ds-1', siteId: 'site-pemalang-ds', name: 'Cable loop holder/plat strip/Cable hanger', qty: 20, unitPrice: 55000 },
          { id: 'm-ds-2', siteId: 'site-pemalang-ds', name: 'Strand Wire Messenger 6 mm', qty: 781, unitPrice: 4050 },
          { id: 'm-ds-3', siteId: 'site-pemalang-ds', name: 'Suspension clamp', qty: 9, unitPrice: 12500 },
          { id: 'm-ds-4', siteId: 'site-pemalang-ds', name: 'Clamps Dead End Fittings/clamp buaya', qty: 90, unitPrice: 11000 },
          { id: 'm-ds-5', siteId: 'site-pemalang-ds', name: 'Label Pole', qty: 54, unitPrice: 7500 },
          { id: 'm-ds-6', siteId: 'site-pemalang-ds', name: 'Label FAT (include QR Code)', qty: 19, unitPrice: 7500 },
          { id: 'm-ds-7', siteId: 'site-pemalang-ds', name: 'Label FDT', qty: 1, unitPrice: 7500 },
          { id: 'm-ds-8', siteId: 'site-pemalang-ds', name: 'Label Cable (on pole, in Handhole)', qty: 5, unitPrice: 7500 },
          { id: 'm-ds-9', siteId: 'site-pemalang-ds', name: 'Plate belt 20mm', qty: 80, unitPrice: 2700 },
          { id: 'm-ds-10', siteId: 'site-pemalang-ds', name: 'Bulldog grip', qty: 117, unitPrice: 2700 },
          { id: 'm-ds-11', siteId: 'site-pemalang-ds', name: 'Pole clamp single', qty: 45, unitPrice: 11000 },
        ],
      },
      {
        id: 'site-pemalang-sf',
        spkId: 'spk-pemalang',
        name: 'PULLING SUBFEEDER DUSUN MANGUNSARI TEGALSARI BARAT PEMALANG',
        sowType: 'Subfeeder',
        poAmount: 11728000,
        mandorId: 'mandor-1',
        mandorName: 'Mandor ADW Mandiri (Pak Fatrah)',
        paymentTerms: [
          { id: 'term-sf-1', siteId: 'site-pemalang-sf', termNumber: 1, percentage: 30, amount: 2052090, isPaid: true, paidDate: '2026-08-15', note: 'Termin 1 Mandor (30% Jasa DP)' },
          { id: 'term-sf-2', siteId: 'site-pemalang-sf', termNumber: 2, percentage: 40, amount: 2736120, isPaid: false, note: 'Termin 2 Mandor' },
          { id: 'term-sf-3', siteId: 'site-pemalang-sf', termNumber: 3, percentage: 30, amount: 2052090, isPaid: false, note: 'Termin 3 Mandor' },
        ],
        permitItems: [],
        services: [
          { id: 'j-sf-1', siteId: 'site-pemalang-sf', name: 'FO core type SM G.652.D-ADSS 24 cores', qty: 1773, uom: 'Meter', unitPrice: 2100, remark: 'Include Pemasangan Label Kabel', actualProgress: 1773 },
          { id: 'j-sf-2', siteId: 'site-pemalang-sf', name: 'Pemasangan Tiang 7 meter 4", STEL L-003 1996', qty: 26, uom: 'Set', unitPrice: 110000, remark: 'Include Pemasangan Pole Clamp Single & Label Tihang', actualProgress: 0 },
          { id: 'j-sf-3', siteId: 'site-pemalang-sf', name: 'Cable loop holder/plat strip/Cable hanger', qty: 5, uom: 'Set', unitPrice: 5000, remark: 'Include Pemasangan Plate Belt', actualProgress: 0 },
          { id: 'j-sf-4', siteId: 'site-pemalang-sf', name: 'Clamps Dead End Fittings/clamp buaya', qty: 16, uom: 'Pcs', unitPrice: 2000, remark: 'Include Pemasangan Suspension Clamp', actualProgress: 0 },
          { id: 'j-sf-5', siteId: 'site-pemalang-sf', name: 'Splicing', qty: 10, uom: 'Core', unitPrice: 20000, remark: '', actualProgress: 0 },
        ],
        materials: [
          { id: 'm-sf-1', siteId: 'site-pemalang-sf', name: 'Cable loop holder/plat strip/Cable hanger', qty: 5, unitPrice: 55000 },
          { id: 'm-sf-2', siteId: 'site-pemalang-sf', name: 'Suspension clamp', qty: 8, unitPrice: 12500 },
          { id: 'm-sf-3', siteId: 'site-pemalang-sf', name: 'Clamps Dead End Fittings/clamp buaya', qty: 16, unitPrice: 11000 },
          { id: 'm-sf-4', siteId: 'site-pemalang-sf', name: 'Label Pole', qty: 26, unitPrice: 7500 },
          { id: 'm-sf-5', siteId: 'site-pemalang-sf', name: 'Label Cable (on pole, in Handhole)', qty: 40, unitPrice: 7500 },
          { id: 'm-sf-6', siteId: 'site-pemalang-sf', name: 'Plate belt 20mm', qty: 20, unitPrice: 2700 },
          { id: 'm-sf-7', siteId: 'site-pemalang-sf', name: 'Pole clamp single', qty: 32, unitPrice: 11000 },
        ],
      },
    ],
  },
  {
    id: 'spk-tegal-slawi',
    vendorId: 'vendor-fs',
    vendorName: 'FiberStar (FS)',
    scopeType: 'IMPLEMENTATION_ONLY',
    workflowStage: 'PELAKSANAAN',
    spkNumber: 'SPK 08/PT INDOTEK BUANA KARYA/TSN - FTTH SLAWI/VIII/2026',
    clusterName: 'CLUSTER TEGAL SLAWI',
    region: 'Central Java',
    status: 'In Progress',
    createdAt: '2026-08-05',
    notes: [
      'Scope: Implementation Only (Izin sudah klir dari FiberStar)',
      'Material telah disuplai 100%',
    ],
    revisionLogs: [
      { id: 'rev-t1', version: 'v1', date: '2026-08-05', author: 'Budhimansyah', status: 'Approved', note: 'SPK Mandor dirilis ke Pak Sugeng' }
    ],
    signOffs: [
      { role: 'Estimator', name: 'Fatrah Subarkah', date: '2026-08-05', status: 'Done' },
      { role: 'Management', name: 'Teguh Prayoga', date: '2026-08-06', status: 'Approved' }
    ],
    sites: [
      {
        id: 'site-tegal-1',
        spkId: 'spk-tegal-slawi',
        name: 'PULLING DISTRIBUSI AREA SLAWI KULON',
        sowType: 'Distribusi',
        poAmount: 52400000,
        mandorId: 'mandor-2',
        mandorName: 'Mandor Pak Sugeng & Tim',
        paymentTerms: [
          { id: 'term-tg-1', siteId: 'site-tegal-1', termNumber: 1, percentage: 30, amount: 7200000, isPaid: true, paidDate: '2026-08-10', note: 'DP 30% Mandor' },
        ],
        services: [
          { id: 'j-tg-1', siteId: 'site-tegal-1', name: 'FO core type SM G.652.D-ADSS 48 cores', qty: 3500, uom: 'Meter', unitPrice: 2100, actualProgress: 3500 },
          { id: 'j-tg-2', siteId: 'site-tegal-1', name: 'Pemasangan Tiang 7 meter 3 inch', qty: 65, uom: 'Set', unitPrice: 105000, actualProgress: 60 },
          { id: 'j-tg-3', siteId: 'site-tegal-1', name: 'Instal Pole mounted FAT (16 ports)', qty: 28, uom: 'Unit', unitPrice: 100000, actualProgress: 14 },
          { id: 'j-tg-4', siteId: 'site-tegal-1', name: 'Splicing & OPM OTDR', qty: 56, uom: 'Core', unitPrice: 20000, actualProgress: 20 },
        ],
        materials: [
          { id: 'm-tg-1', siteId: 'site-tegal-1', name: 'Strand Wire Messenger 6 mm', qty: 1200, unitPrice: 4050 },
          { id: 'm-tg-2', siteId: 'site-tegal-1', name: 'Clamps Dead End Fittings/clamp buaya', qty: 140, unitPrice: 11000 },
          { id: 'm-tg-3', siteId: 'site-tegal-1', name: 'Label Pole', qty: 65, unitPrice: 7500 },
        ]
      }
    ]
  },
  {
    id: 'spk-pekalongan-utara',
    vendorId: 'vendor-mr',
    vendorName: 'MyRepublic / Moratelindo',
    scopeType: 'END_TO_END',
    workflowStage: 'DRAFT_ESTIMASI',
    spkNumber: 'SPK 12/PT INDOTEK BUANA KARYA/TSN - FTTH PEKALONGAN/VIII/2026',
    clusterName: 'CLUSTER PEKALONGAN UTARA',
    region: 'Central Java',
    status: 'Penawaran',
    createdAt: '2026-08-14',
    notes: [
      'Scope: End-to-End. Estimasi biaya koordinasi RT/RW sedang dikalkulasi estimator.',
    ],
    revisionLogs: [
      { id: 'rev-p1', version: 'v1', date: '2026-08-14', author: 'Fatrah Subarkah', status: 'Penawaran', note: 'Initial proposal & kalkulasi permit' }
    ],
    signOffs: [
      { role: 'Estimator', name: 'Fatrah Subarkah', date: '2026-08-14', status: 'Pending Review' }
    ],
    sites: [
      {
        id: 'site-pkl-1',
        spkId: 'spk-pekalongan-utara',
        name: 'PULLING FEEDER & DISTRIBUSI PANJANG WETAN',
        sowType: 'Distribusi',
        poAmount: 28500000,
        mandorId: 'mandor-4',
        mandorName: 'Mandor Pak Rahmat Pantura',
        paymentTerms: [],
        permitItems: [
          {
            id: 'p-pkl-1',
            siteId: 'site-pkl-1',
            name: 'Perizinan Kawasan Pelabuhan & RT/RW Panjang Wetan',
            category: 'Lingkungan / Warga',
            estimatedCost: 1500000,
            actualCost: 0,
            status: 'In Progress',
            pic: 'Pak Usep Kurnia',
            notes: 'Koordinasi perlintasan rel & pemukiman',
          }
        ],
        services: [
          { id: 'j-pkl-1', siteId: 'site-pkl-1', name: 'FO core type SM G.652.D-ADSS 48 cores', qty: 2100, uom: 'Meter', unitPrice: 2200, actualProgress: 0 },
          { id: 'j-pkl-2', siteId: 'site-pkl-1', name: 'Pemasangan Tiang 7 meter 3 inch', qty: 38, uom: 'Set', unitPrice: 110000, actualProgress: 0 },
        ],
        materials: [
          { id: 'm-pkl-1', siteId: 'site-pkl-1', name: 'Cable loop holder/plat strip/Cable hanger', qty: 25, unitPrice: 55000 },
          { id: 'm-pkl-2', siteId: 'site-pkl-1', name: 'Strand Wire Messenger 6 mm', qty: 900, unitPrice: 4200 },
        ]
      }
    ]
  }
];
